In [1]:
import pandas as pd

In [3]:
students = pd.read_csv("../data/raw/students.csv")

courses = pd.read_csv("../data/raw/courses.csv")

instructors = pd.read_csv("../data/raw/instructors.csv")

enrollments = pd.read_csv("../data/raw/enrollments.csv")

quiz_results = pd.read_csv("../data/raw/quiz_results.csv")

In [4]:
students.head()

,student_id,name,email,age,city,registration_date,acquisition_source,plan_type
0,STU00001,Arif Setyowati,arif.setyowati@gmail.com,45,Yogyakarta,2023-07-23,Google,free
1,STU00002,Indah Hakim,indah.hakim757@yahoo.com,20,Surabaya,2022-09-20,Google,free
2,STU00003,Bayu Kurniawan,bayu.kurniawan@yahoo.com,34,Medan,2023-07-16,Instagram,pro
3,STU00004,Panji Lestari,panji.lestari994@outlook.com,39,Jakarta,2025-02-21,YouTube,pro
4,STU00005,Siti Mahendra,siti.mahendra@gmail.com,45,Jakarta,2023-10-24,Google,free

In [5]:
courses.head()

,course_id,title,category,instructor_id,price_idr,duration_hours,level,avg_rating,total_enrolled,created_date,status
0,CRS001,MySQL untuk Backend Developer,SQL,INST27,399000,5,intermediate,4.0,184,2021-11-27,draft
1,CRS002,Excel untuk HR Analytics,Excel,INST18,499000,21,beginner,4.0,1907,2021-11-02,published
2,CRS003,Dashboard Interaktif dengan Power BI,Power BI,INST27,399000,22,beginner,4.5,773,2021-03-23,published
3,CRS004,ETL Pipeline dengan Python,Data Engineering,INST07,0,25,intermediate,4.2,1998,2024-02-21,published
4,CRS005,Advanced Formulas: INDEX MATCH XLOOKUP,Excel,INST14,599000,27,beginner,4.1,140,2023-04-25,published

In [6]:
instructors.head()

,instructor_id,name,expertise,city,courses_count,avg_rating,joined_date
0,INST01,Umi Damayanti,SQL & Data Engineering,Surabaya,2,4.7,2021-12-15
1,INST02,Nadia Putra,Excel & Google Sheets,Bandung,1,4.2,2021-04-10
2,INST03,Winda Ramadhan,Statistics & Analytics,Jakarta,3,4.8,2023-01-18
3,INST04,Kirana Hidayat,Power BI & Tableau,Medan,1,4.6,2023-04-30
4,INST05,Mawar Putra,Data Visualization,Yogyakarta,1,4.1,2021-08-22

In [7]:
enrollments.head()

,enrollment_id,student_id,course_id,enrolled_date,completion_date,completion_pct,certificate_issued,last_accessed
0,ENR000001,STU00001,CRS038,2024-12-28,2025-01-22,100,True,2025-02-12
1,ENR000002,STU00001,CRS010,2024-11-10,NaN,7,False,2025-01-24
2,ENR000003,STU00001,CRS022,2025-01-30,2025-02-18,100,True,2025-02-19
3,ENR000004,STU00001,CRS033,2023-12-22,2024-02-18,100,True,2024-03-02
4,ENR000005,STU00001,CRS018,2025-01-16,2025-01-21,100,True,2025-01-27

In [8]:
quiz_results.head()

,quiz_id,enrollment_id,student_id,course_id,quiz_number,attempt_number,score,passed,attempt_date
0,QZ000001,ENR000001,STU00001,CRS038,1,1,76,True,2025-01-24
1,QZ000002,ENR000001,STU00001,CRS038,2,1,87,True,2025-01-19
2,QZ000003,ENR000001,STU00001,CRS038,3,1,62,False,2025-02-03
3,QZ000004,ENR000001,STU00001,CRS038,3,2,74,True,2025-01-13
4,QZ000005,ENR000001,STU00001,CRS038,4,1,40,False,2025-01-30

In [10]:
datasets = {
    "Students": students,
    "Courses": courses,
    "Instructors": instructors,
    "Enrollments": enrollments,
    "Quiz Results": quiz_results
}

In [11]:
for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)

    print("Shape :", df.shape)
    print()

    print(df.info())

============================================================
Students
============================================================
Shape : (3000, 8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          3000 non-null   object
 1   name                3000 non-null   object
 2   email               3000 non-null   object
 3   age                 3000 non-null   int64
 4   city                3000 non-null   object
 5   registration_date   3000 non-null   object
 6   acquisition_source  3000 non-null   object
 7   plan_type           3000 non-null   object
dtypes: int64(1), object(7)
memory usage: 187.6+ KB
None
============================================================
Courses
============================================================
Shape : (50, 11)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   course_id       50 non-null     object
 1   title           50 non-null     object
 2   category        50 non-null     object
 3   instructor_id   50 non-null     object
 4   price_idr       50 non-null     int64
 5   duration_hours  50 non-null     int64
 6   level           50 non-null     object
 7   avg_rating      50 non-null     float64
 8   total_enrolled  50 non-null     int64
 9   created_date    50 non-null     object
 10  status          50 non-null     object
dtypes: float64(1), int64(3), object(7)
memory usage: 4.4+ KB
None
============================================================
Instructors
============================================================
Shape : (30, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   instructor_id  30 non-null     object
 1   name           30 non-null     object
 2   expertise      30 non-null     object
 3   city           30 non-null     object
 4   courses_count  30 non-null     int64
 5   avg_rating     30 non-null     float64
 6   joined_date    30 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 1.8+ KB
None
============================================================
Enrollments
============================================================
Shape : (10380, 8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10380 entries, 0 to 10379
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   enrollment_id       10380 non-null  object
 1   student_id          10380 non-null  object
 2   course_id           10380 non-null  object
 3   enrolled_date       10380 non-null  object
 4   completion_date     3188 non-null   object
 5   completion_pct      10380 non-null  int64
 6   certificate_issued  10380 non-null  bool
 7   last_accessed       10380 non-null  object
dtypes: bool(1), int64(1), object(6)
memory usage: 577.9+ KB
None
============================================================
Quiz Results
============================================================
Shape : (30875, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30875 entries, 0 to 30874
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   quiz_id         30875 non-null  object
 1   enrollment_id   30875 non-null  object
 2   student_id      30875 non-null  object
 3   course_id       30875 non-null  object
 4   quiz_number     30875 non-null  int64
 5   attempt_number  30875 non-null  int64
 6   score           30875 non-null  int64
 7   passed          30875 non-null  bool
 8   attempt_date    30875 non-null  object
dtypes: bool(1), int64(3), object(5)
memory usage: 1.9+ MB
None

In [12]:
for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)

    print(df.isnull().sum())
    print()

============================================================
Students
============================================================
student_id            0
name                  0
email                 0
age                   0
city                  0
registration_date     0
acquisition_source    0
plan_type             0
dtype: int64

============================================================
Courses
============================================================
course_id         0
title             0
category          0
instructor_id     0
price_idr         0
duration_hours    0
level             0
avg_rating        0
total_enrolled    0
created_date      0
status            0
dtype: int64

============================================================
Instructors
============================================================
instructor_id    0
name             0
expertise        0
city             0
courses_count    0
avg_rating       0
joined_date      0
dtype: int64

============================================================
Enrollments
============================================================
enrollment_id            0
student_id               0
course_id                0
enrolled_date            0
completion_date       7192
completion_pct           0
certificate_issued       0
last_accessed            0
dtype: int64

============================================================
Quiz Results
============================================================
quiz_id           0
enrollment_id     0
student_id        0
course_id         0
quiz_number       0
attempt_number    0
score             0
passed            0
attempt_date      0
dtype: int64

In [13]:
for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)

    print("Duplicate :", df.duplicated().sum())
    print()

============================================================
Students
============================================================
Duplicate : 0

============================================================
Courses
============================================================
Duplicate : 0

============================================================
Instructors
============================================================
Duplicate : 0

============================================================
Enrollments
============================================================
Duplicate : 0

============================================================
Quiz Results
============================================================
Duplicate : 0